/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"
#include "nsIDOMDOMRequest.idl"
#include "nsISupports.idl"

/*interface nsIDOMEventListener;*/

[scriptable, uuid(1e997036-e955-4b91-88f0-36424d1c9ba9)]
interface nsIDOMHotkeyManager : nsISupports
{
  readonly attribute long homeKey;
  readonly attribute long muteKey;
  readonly attribute long volumeUpKey;
  readonly attribute long volumeDownKey;

  void beginEditHotkey();
  void endEditHotkey();

  void setHomeKey(in unsigned long key);
  void setMuteKey(in unsigned long key);
  void setVolumeUpKey(in unsigned long key);
  void setVolumeDownKey(in unsigned long key);

  attribute nsIDOMEventListener onHotkeySetResult;
};
