#include "nsISupports.idl"


[scriptable, uuid(d1fe6e76-5238-4b68-aaa7-6d8598a13a3f)]
interface nsIHWKeyboardObserver: nsISupports
{
    readonly attribute bool present;

	void notifyHWKeyboardChanged(in bool isAdded);
};
