/*
 * trungnt
 */

#include "nsIDOMEventTarget.idl"
#include "nsIDOMDOMRequest.idl"
#include "nsISupports.idl"

/*interface nsIDOMEventListener;*/

[scriptable, uuid(349e6321-7972-4871-9fb7-94bfb855ba43)]
interface nsIDOMEthernetManager : nsISupports
{
  void enable();
  void disable();

/*  void connect();
  void disconnect();
  void reconnect();*/

  void setdhcp(in boolean dhcpcd);
  void setstaticipconfig(in jsval config);
  void setaddr(in string addr);
  void setnetmask(in string mask);
  void setgateway(in string gateway);
  void setdns1(in string dns1);
  void setdns2(in string dns2);

  readonly attribute boolean    present;
  readonly attribute boolean    enabled;
  readonly attribute boolean    connected;
  readonly attribute jsval      connection;

  attribute nsIDOMEventListener onenabledchanged;
  attribute nsIDOMEventListener onconnectedchanged;
  attribute nsIDOMEventListener connectionupdated;
  /*attribute jsval onenabledchange;
  attribute jsval onconnectedchange;*/
};
